alert("Meu");
alert("amor");
alert("é");
alert("a");
alert("Gabriela");
alert("Ah!!!!");
alert("É a verdade");
alert("Meu amor é a Gabriela.");
alert("Mas");
alert("também");
alert("é");
alert("o");
alert("Daniel");
alert("e");
alert("também");
alert("a");
alert("Lilica");
alert("Meu amor é a minha família!");
